#! /bin/sh
set -e

#DEBHELPER#

case "$1" in
  configure)
    mkdir -p /usr/share/ubuntu-artwork/home
    update-alternatives \
      --install /usr/share/ubuntu-artwork/home/index.html \
      firefox-homepage /usr/share/xubuntu-docs/about/xubuntu-index.html 40 \
      --slave /usr/share/ubuntu-artwork/home/locales \
      firefox-homepage-locales /usr/share/xubuntu-docs/about/locales

  ;;
esac

exit 0
