#! /bin/sh
set -e

#DEBHELPER#

case "$1" in
  configure)
    update-alternatives \
      --install /usr/share/ubuntu-artwork/home/index.html \
      firefox-homepage /usr/share/ubuntu-artwork/home/firefox-index.html 40

  ;;
esac

exit 0
