#! /bin/sh
set -e

#DEBHELPER#

case "$1" in
  configure)
    update-alternatives \
      --install /usr/share/ubuntu-artwork/home/index.html \
      firefox-homepage /usr/share/ubuntu-artwork/home/firefox-index.html 40 \
      --slave /usr/share/ubuntu-artwork/home/locales \
      firefox-homepage-locales /usr/share/ubuntu-artwork/home/locales-ubuntu

    if which install-docs >/dev/null 2>&1; then
       install-docs -i /usr/share/doc-base/ubuntu-aboutubuntu
       install-docs -i /usr/share/doc-base/ubuntu-desktopguide
       install-docs -i /usr/share/doc-base/ubuntu-serverguide
    fi

  ;;
esac

exit 0
