#! /bin/sh
set -e

#DEBHELPER#

case "$1" in
  remove|deconfigure|failed-upgrade)
    update-alternatives --remove firefox-homepage \
	/usr/share/ubuntu-artwork/home/firefox-index.html

    if which install-docs >/dev/null 2>&1; then
      install-docs -r ubuntu-aboutubuntu
      install-docs -r ubuntu-desktopguide
      install-docs -r ubuntu-serverguide
    fi

  ;;
esac
