#! /bin/sh
set -e

#DEBHELPER#

case "$1" in
  configure)
    update-alternatives \
      --install /usr/share/ubuntu-artwork/home/index.html \
      firefox-homepage /usr/share/doc/kde/HTML/en/kubuntu/about-kubuntu/index.html 40

    if which install-docs >/dev/null 2>&1; then
       install-docs -i /usr/share/doc-base/kubuntu-desktopguide
       install-docs -i /usr/share/doc-base/kubuntu-serverguide
       install-docs -i /usr/share/doc-base/kubuntu-packagingguide
    fi


  ;;
esac

exit 0
