#! /bin/sh
set -e

#DEBHELPER#

case "$1" in
  remove|deconfigure|failed-upgrade)
    update-alternatives --auto firefox-homepage
    update-alternatives --remove firefox-homepage \
    /usr/share/ubuntu-artwork/home/kfirefox-index.html

    if which install-docs >/dev/null 2>&1; then
      install-docs -r /usr/share/doc-base/kubuntu-systemdocs
      rm -rf /usr/share/doc/kde/HTML/en/kubuntu
    fi


  ;;
esac
